server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/meeting
    username: kodpit
    password: kodpit
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org.springframework.security: DEBUG